"""Command line side of location reminders: the cron checker and its setup."""

from __future__ import annotations

import asyncio
import os
import shlex
import shutil
import sys
from pathlib import Path

from . import reminders as rem
from .client import RecorderClient
from .config import ConfigError, Settings, recorder_env
from .service import OwnTracksService

SCRIPT_NAME = "owntracks-reminders.sh"


def run_check(data_dir: Path | None = None) -> int:
    """One checker pass. Prints messages to deliver; prints nothing when quiet.

    Hermes no-agent cron jobs deliver stdout verbatim and treat empty output as
    a silent tick, so this must stay quiet unless a reminder fires.
    """
    store = rem.ReminderStore(data_dir or rem.data_dir())
    if not store.path.exists():
        return 0  # no reminder was ever created

    env = {**store.load_recorder_config(), **recorder_env()}
    try:
        settings = Settings.from_env(env)
    except ConfigError as exc:
        with store.transaction() as data:
            if data["checker"].get("config_alerted"):
                return 0
            data["checker"]["config_alerted"] = True
        print(f"⚠️ OwnTracks reminders cannot run: {exc}")
        return 0
    with store.transaction() as data:
        data["checker"].pop("config_alerted", None)

    async def _run() -> list[str]:
        client = RecorderClient(settings)
        try:
            return await OwnTracksService(settings, client, store=store).check_reminders()
        finally:
            await client.aclose()

    messages = asyncio.run(_run())
    if messages:
        print("\n\n".join(messages))
    return 0


def _executable() -> str:
    found = shutil.which("owntracks-mcp")
    return str(Path(found or sys.argv[0]).resolve())


def setup_reminders(hermes_home: Path | None, data_dir: Path | None, deliver: str) -> int:
    hermes_home = (hermes_home or Path(os.environ.get("HERMES_HOME") or "~/.hermes")).expanduser()
    data_dir = (data_dir or rem.data_dir()).expanduser()
    exe = _executable()

    scripts = hermes_home / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    script = scripts / SCRIPT_NAME
    script.write_text(
        "#!/usr/bin/env bash\n"
        "# Generated by `owntracks-mcp setup-reminders`: one location-reminder check.\n"
        "# Prints nothing unless a reminder fires.\n"
        f"export OWNTRACKS_DATA_DIR={shlex.quote(str(data_dir))}\n"
        f"exec {shlex.quote(exe)} check-reminders\n",
        encoding="utf-8",
    )
    script.chmod(0o755)

    print(f"Wrote {script}")
    print(f"  checker:   {exe}")
    print(f"  data dir:  {data_dir}")
    if "/.cache/" in exe or "archive-v" in exe:
        print(
            "\nWarning: owntracks-mcp is running from a temporary uvx cache. Install it permanently\n"
            "so the path above stays valid:  uv tool install git+https://github.com/de-niji/OwnTracksHermes\n"
            "and run `owntracks-mcp setup-reminders` again."
        )
    print(
        "\nNow create the cron job (replace the delivery target with your own, e.g.\n"
        "telegram, signal:+49..., discord:#channel):\n\n"
        f'  hermes cron create "every 1m" --no-agent --script {SCRIPT_NAME} \\\n'
        f"    --deliver {shlex.quote(deliver)} --name owntracks-reminders\n\n"
        "Then ask Hermes for a reminder, e.g. \"remind me to buy milk when I get to work\"."
    )
    return 0
